# Battery configuration

# Battery voltage sensor
sensor:
  - platform: adc
    pin: $battery_pin
    name: $node_prefix batteri
    icon: mdi:battery
    attenuation: auto
    filters:
      - multiply: $battery_factor

# Charging voltage sensor
  - platform: adc
    pin: $charging_pin
    name: $node_prefix laddning
    icon: mdi:lightning-bolt
    attenuation: auto
    filters:
      - multiply: $charging_factor
