# Battery configuration

# Battery voltage sensor
sensor:
  - platform: adc
    pin: $battery_pin
    name: $node_prefix batteri
    icon: mdi:battery
    attenuation: auto
    filters:
      - exponential_moving_average:
          alpha: 0.06
          send_every: 3
          send_first_at: 1
      - multiply: $battery_factor

# Charging voltage sensor
  - platform: adc
    pin: $charging_pin
    name: $node_prefix laddning
    icon: mdi:lightning-bolt
    attenuation: auto
    filters:
      - exponential_moving_average:
          alpha: 0.06
          send_every: 3
          send_first_at: 1
      - multiply: $charging_factor
