# Board configurations

# Olimex ESP32-DevKit-LiPo
esp32:
  board:    esp32-devkitlipo
  framework:
    type: esp-idf
packages:
  wifi: !include wifi.yaml
substitutions:
  # status.yaml
  system_led_pin:      GPIO32
  controller_led_pin:  GPIO33
  # control-mixing_valve.yaml
  relay_decrease_pin:  GPIO25   # GPIO16
  relay_increase_pin:  GPIO26   # GPIO17
  # sensors-outdoor_temp.yaml
  digital_temp_pin:    GPIO14   # GPIO26
  analog_temp_pin:     GPIO34
  analog_power_pin:    GPIO13   # GPIO27
  # sensors-line_temp.yaml
  line_temp_pin:       GPIO27   # GPIO25
  # battery.yaml
  battery_pin:         GPIO35
  charging_pin:        GPIO39
  battery_factor:      '1.784'   # 3.3V/3.7V*2.0, voltage divider (470+470)/470kohm
  charging_factor:     '1.468'   # 5.0V/5.0V*1.4681, voltage divider (220+470)/470kohm

## Olimex ESP32-C3-DevKit-Lipo
#esp32:
#  board:    esp32-c3-devkitm-1
#  framework:
#    type: esp-idf
#packages:
#  wifi: !include wifi.yaml
#substitutions:
#  # status.yaml
#  system_led_pin:      GPIO1
#  controller_led_pin:  GPIO2
#  # sensors-outdoor_temp.yaml
#  digital_temp_pin:    GPIO7
#  analog_temp_pin:     GPIO5
#  analog_power_pin:    GPIO6
#  # battery.yaml
#  battery_pin:         GPIO3
#  charging_pin:        GPIO4
#  battery_factor:      '1.784'   # 3.3V/3.7V*2.0, voltage divider (470+470)/470kohm
#  charging_factor:     '1.468'   # 5.0V/5.0V*1.4681, voltage divider (220+470)/470kohm

## Olimex ESP32-POE-ISO
#esp32:
#  board:    esp32-poe-iso
#  framework:
#    type: esp-idf
#packages:
#  ethernet: !include ethernet.yaml
#substitutions:
#  # status.yaml
#  system_led_pin:      GPIO32
#  controller_led_pin:  GPIO33
#  # sensors-outdoor_temp.yaml
#  digital_temp_pin:    GPIO14
#  analog_temp_pin:     GPIO34
#  analog_power_pin:    GPIO13
#  # battery.yaml
#  battery_pin:         GPIO35
#  charging_pin:        GPIO39
#  battery_factor:      '1.784'   # 3.3V/3.7V*2.0, voltage divider (470+470)/470kohm
#  charging_factor:     '1.470'   # 5.0V/5.0V*1.4700, voltage divider (47+100)/100kohm
