# Controls definitions

# Default operational mode
esphome:
  on_boot:
    priority: 200
    then:
      - switch.turn_on: ${node_name}_controller_mode

# Operational switches
switch:
  # Operational mode
  - platform: template
    name: $node_prefix automatiskt driftläge
    id: ${node_name}_controller_mode
    icon: mdi:thermostat-auto
    restore_mode: ALWAYS_ON
    # Automatic mode
    turn_on_action:
      - lambda: |-
          id(mixing_valve_manual_decrease).turn_off();
          id(mixing_valve_manual_increase).turn_off();
          id(${node_name}_controller_mode).publish_state(true);
    # Manual mode
    turn_off_action:
      - lambda: |-
          id(decrease_relay).turn_off();
          id(increase_relay).turn_off();
          id(${node_name}_controller_mode).publish_state(false);

  # Manual decrease
  - platform: template
    name: $node_prefix blandning minska
    id: mixing_valve_manual_decrease
    icon: mdi:arrow-down-drop-circle
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            if ( id(increase_relay).state )
              id(increase_relay).turn_off();
            id(decrease_relay).turn_on();
            id(mixing_valve_manual_decrease).publish_state(true);
          }
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            if ( id(decrease_relay).state )
              id(decrease_relay).turn_off();
            id(mixing_valve_manual_decrease).publish_state(false);
          }
  # Manual increase
  - platform: template
    name: $node_prefix blandning öka
    id: mixing_valve_manual_increase
    icon: mdi:arrow-up-drop-circle
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            if ( id(decrease_relay).state )
              id(decrease_relay).turn_off();
            id(increase_relay).turn_on();
            id(mixing_valve_manual_increase).publish_state(true);
          }
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            if ( id(increase_relay).state )
              id(increase_relay).turn_off();
            id(mixing_valve_manual_increase).publish_state(false);
          }

# Buttons
button:
  # Manual neutral
  - platform: template
    name: $node_prefix blandning neutral
    id: mixing_valve_manual_neutral
    icon: mdi:stop-circle
    on_press:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            if ( id(mixing_valve_manual_increase).state )
              id(mixing_valve_manual_increase).turn_off();
            if ( id(mixing_valve_manual_decrease).state )
              id(mixing_valve_manual_decrease).turn_off();
          }
