# Mixing valve controller configuration

# Relay configuration
switch:
  # Relay actuator decrease
  - platform: gpio
    id: decrease_relay
    interlock: [ increase_relay ]
    pin:
      number: GPIO25
      inverted: true
    on_turn_on:
      - delay: 400ms
      - switch.turn_off: decrease_relay
  # Relay actuator increase
  - platform: gpio
    id: increase_relay
    interlock: [ decrease_relay ]
    pin:
      number: GPIO26
      inverted: true
    on_turn_on:
      - delay: 400ms
      - switch.turn_off: increase_relay

  # Mixing valve actuator decrease
  - platform: template
    id: ${node_name}_mixing_valve_actuator_decrease
    optimistic: true
    on_turn_on:
      - while:
          condition:
            switch.is_on: ${node_name}_mixing_valve_actuator_decrease
          then:
            - switch.turn_on: decrease_relay
            - number.decrement:
                id: ${node_name}_mixing_valve_position_counter
                cycle: false
            - if:
                condition:
                  switch.is_on: ${node_name}_controller_mode
                then:
                  - delay: 4s
                else:
                  - delay: 1s
  # Mixing valve actuator increase
  - platform: template
    id: ${node_name}_mixing_valve_actuator_increase
    optimistic: true
    on_turn_on:
      - while:
          condition:
            switch.is_on: ${node_name}_mixing_valve_actuator_increase
          then:
            - switch.turn_on: increase_relay
            - number.increment:
                id: ${node_name}_mixing_valve_position_counter
                cycle: false
            - if:
                condition:
                  switch.is_on: ${node_name}_controller_mode
                then:
                  - delay: 4s
                else:
                  - delay: 1s

# Supply line modulation level sensors
sensor:
  # Supply line modulation level decrease
  - platform: template
    name: $node_prefix reglernivå minska
    id: ${node_name}_supply_line_modulation_level_decrease
    icon: mdi:chart-bell-curve-cumulative
    accuracy_decimals: 1
    lambda: |-
       return 0.0;

  # Supply line modulation level increase
  - platform: template
    name: $node_prefix reglernivå öka
    id: ${node_name}_supply_line_modulation_level_increase
    icon: mdi:chart-bell-curve-cumulative
    accuracy_decimals: 1
    lambda: |-
       return 0.0;

# Thermostat configuration

# Supply line temperature controller
climate:
  - platform: thermostat
    name: $node_prefix framledningsreglering
    id: ${node_name}_supply_line_controller
    sensor: ${node_name}_supply_line_temperature
    min_cooling_off_time: 1s
    min_cooling_run_time: 1s
    min_heating_off_time: 1s
    min_heating_run_time: 1s
    min_idle_time: 1s
    set_point_minimum_differential: 0.4°C
    cool_deadband: 0.2°C
    cool_overrun:  0.2°C
    heat_deadband: 0.2°C
    heat_overrun:  0.2°C
    cool_action:
      - if:
          condition:
            - switch.is_on: ${node_name}_controller_mode
          then:
            - switch.turn_off: ${node_name}_mixing_valve_actuator_increase
            - switch.turn_on:  ${node_name}_mixing_valve_actuator_decrease
    heat_action:
      - if:
          condition:
            - switch.is_on: ${node_name}_controller_mode
          then:
            - switch.turn_off: ${node_name}_mixing_valve_actuator_decrease
            - switch.turn_on:  ${node_name}_mixing_valve_actuator_increase
    idle_action:
      - if:
          condition:
            - switch.is_on: ${node_name}_controller_mode
          then:
            - switch.turn_off: ${node_name}_mixing_valve_actuator_decrease
            - switch.turn_off: ${node_name}_mixing_valve_actuator_increase
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low:  21.4°C
        default_target_temperature_high: 21.0°C
      - name: Away
        default_target_temperature_low:  18.4°C
        default_target_temperature_high: 18.0°C
    visual:
      min_temperature: 15.0°C
      max_temperature: 35.0°C
      temperature_step: 0.1°C

# Mixing valve actuator operational indicators
binary_sensor:
  # Decrease
  - platform: template
    name: $node_prefix minska
    id: ${node_name}_mixing_valve_status_decrease
    icon: mdi:minus-circle
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( id(${node_name}_mixing_valve_actuator_decrease).state )
          return true;
      } else {
        if ( id(mixing_valve_manual_decrease).state )
          return true;
      }
      return false;
  # Neutral
  - platform: template
    name: $node_prefix neutral
    id: ${node_name}_mixing_valve_status_neutral
    icon: mdi:circle-outline
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( (id(${node_name}_mixing_valve_actuator_decrease).state == 0) && 
             (id(${node_name}_mixing_valve_actuator_increase).state == 0) )
          return true;
      } else {
        if ( (id(mixing_valve_manual_decrease).state == 0) &&
             (id(mixing_valve_manual_increase).state == 0) )
          return true;
      }
      return false;
  # Increase
  - platform: template
    name: $node_prefix öka
    id: ${node_name}_mixing_valve_status_increase
    icon: mdi:plus-circle
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( id(${node_name}_mixing_valve_actuator_increase).state )
          return true;
      } else {
        if ( id(mixing_valve_manual_increase).state )
          return true;
      }
      return false;

# Mixing valve actuator position counter
number:
  - platform: template
    name: $node_prefix läge
    id: ${node_name}_mixing_valve_position_counter
    icon: mdi:knob
    min_value: 0
    max_value: 240
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true
