# Controls definitions

# Default operational mode
esphome:
  on_boot:
    priority: 200
    then:
      - switch.turn_on: ${node_name}_controller_mode

# Operational switches
switch:
  # Operational mode
  - platform: template
    name: Automatiskt driftläge
    id: ${node_name}_controller_mode
    icon: mdi:thermostat-auto
    restore_mode: ALWAYS_ON
    # Automatic mode
    turn_on_action:
      - lambda: |-
          id(mixing_valve_manual_decrease).turn_off();
          id(mixing_valve_manual_increase).turn_off();
          id(${node_name}_mixing_valve_position_hold).turn_off();
          id(${node_name}_controller_mode).publish_state(true);
          id(${node_name}_outdoor_temp_compensated_mode).publish_state(true);
      - climate.control:
          id: ${node_name}_supply_line_controller
          mode: "HEAT_COOL"
    # Manual mode
    turn_off_action:
      - lambda: |-
          id(${node_name}_mixing_valve_actuator_decrease).turn_off();
          id(${node_name}_mixing_valve_actuator_increase).turn_off();
          id(${node_name}_mixing_valve_position_hold).turn_off();
          id(${node_name}_controller_mode).publish_state(false);
          id(${node_name}_outdoor_temp_compensated_mode).publish_state(false);
      - climate.control:
          id: ${node_name}_supply_line_controller
          mode: "OFF"

  # Manual decrease
  - platform: template
    name: Blandning minska
    id: mixing_valve_manual_decrease
    icon: mdi:arrow-down-drop-circle
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            if ( id(${node_name}_mixing_valve_actuator_increase).state )
              id(${node_name}_mixing_valve_actuator_increase).turn_off();
            if ( id(mixing_valve_manual_increase).state )
              id(mixing_valve_manual_increase).turn_off();
            id(mixing_valve_manual_decrease).publish_state(true);
            id(${node_name}_mixing_valve_actuator_decrease).turn_on();
          }
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            id(${node_name}_mixing_valve_actuator_decrease).turn_off();
            id(mixing_valve_manual_decrease).publish_state(false);
          }
  # Manual increase
  - platform: template
    name: Blandning öka
    id: mixing_valve_manual_increase
    icon: mdi:arrow-up-drop-circle
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            if ( id(${node_name}_mixing_valve_actuator_decrease).state )
              id(${node_name}_mixing_valve_actuator_decrease).turn_off();
            if ( id(mixing_valve_manual_decrease).state )
              id(mixing_valve_manual_decrease).turn_off();
            id(mixing_valve_manual_increase).publish_state(true);
            id(${node_name}_mixing_valve_actuator_increase).turn_on();
          }
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            id(${node_name}_mixing_valve_actuator_increase).turn_off();
            id(mixing_valve_manual_increase).publish_state(false);
          }
  # Actuator hold position
  - platform: template
    name: Lägeshållning
    id: ${node_name}_mixing_valve_position_hold
    icon: mdi:pause-circle
    turn_on_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(${node_name}_mixing_valve_position_hold).publish_state(true);
    turn_off_action:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state )
            id(${node_name}_mixing_valve_position_hold).publish_state(false);

# Buttons
button:
  # Manual neutral
  - platform: template
    name: Blandning neutral
    id: mixing_valve_manual_neutral
    icon: mdi:stop-circle
    on_press:
      - lambda: |-
          if ( id(${node_name}_controller_mode).state == 0 ) {
            if ( id(mixing_valve_manual_increase).state )
              id(mixing_valve_manual_increase).turn_off();
            if ( id(mixing_valve_manual_decrease).state )
              id(mixing_valve_manual_decrease).turn_off();
          }
