# Mixing valve controller configuration

# Relay configuration
switch:
  # Relay actuator decrease
  - platform: gpio
    id: decrease_relay
    interlock: [ increase_relay ]
    pin:
      number: GPIO25
      inverted: true
    on_turn_on:
      - delay: 400ms
      - switch.turn_off: decrease_relay
  # Relay actuator increase
  - platform: gpio
    id: increase_relay
    interlock: [ decrease_relay ]
    pin:
      number: GPIO26
      inverted: true
    on_turn_on:
      - delay: 400ms
      - switch.turn_off: increase_relay

  # Mixing valve actuator decrease
  - platform: template
    id: ${node_name}_mixing_valve_actuator_decrease
    optimistic: true
    on_turn_on:
      - while:
          condition:
            switch.is_on: ${node_name}_mixing_valve_actuator_decrease
          then:
            - switch.turn_on: decrease_relay
            - number.decrement:
                id: ${node_name}_mixing_valve_position_counter
                cycle: false
            - if:
                condition:
                  switch.is_on: ${node_name}_controller_mode
                then:
                  - delay: 4s
                else:
                  - delay: 1s
  # Mixing valve actuator increase
  - platform: template
    id: ${node_name}_mixing_valve_actuator_increase
    optimistic: true
    on_turn_on:
      - while:
          condition:
            switch.is_on: ${node_name}_mixing_valve_actuator_increase
          then:
            - switch.turn_on: increase_relay
            - number.increment:
                id: ${node_name}_mixing_valve_position_counter
                cycle: false
            - if:
                condition:
                  switch.is_on: ${node_name}_controller_mode
                then:
                  - delay: 4s
                else:
                  - delay: 1s

# Supply line modulation level sensors
sensor:
  # Supply line modulation level decrease
  - platform: template
    name: $node_prefix reglernivå minska
    id: ${node_name}_supply_line_modulation_level_decrease
    icon: mdi:chart-bell-curve-cumulative
    accuracy_decimals: 1
    lambda: |-
      float mod_level = 0.0;
      if ( id(${node_name}_controller_mode).state ) {
        float temp_sp = id(${node_name}_supply_line_target_temperature).state;
        float temp_cu = id(${node_name}_supply_line_temperature).state;
        float temp_diff =  temp_cu - temp_sp;
        if ( temp_diff > 0.0 ) {
          if ( temp_diff < 0.4 )
            mod_level = 10.0;
          if ( temp_diff < 1.2 )
            mod_level = 40.0;
          else
            mod_level = 100.0;
        }
      }
      return mod_level;
  # Supply line modulation level increase
  - platform: template
    name: $node_prefix reglernivå öka
    id: ${node_name}_supply_line_modulation_level_increase
    icon: mdi:chart-bell-curve-cumulative
    accuracy_decimals: 1
    lambda: |-
      float mod_level = 0.0;
      if ( id(${node_name}_controller_mode).state ) {
        float temp_sp = id(${node_name}_supply_line_target_temperature).state;
        float temp_cu = id(${node_name}_supply_line_temperature).state;
        float temp_diff =  temp_sp - temp_cu;
        if ( temp_diff > 0.0 ) {
          if ( temp_diff < 0.4 )
            mod_level = 10.0;
          if ( temp_diff < 1.2 )
            mod_level = 40.0;
          else
            mod_level = 100.0;
        }
      }
      return mod_level;

# Thermostat configuration

# Supply line temperature controller
climate:
  - platform: thermostat
    name: $node_prefix framledningsreglering
    id: ${node_name}_supply_line_controller
    sensor: ${node_name}_supply_line_temperature
    set_point_minimum_differential: 0.2°C
    # Decrease mixing ratio
    min_cooling_off_time: 1s
    min_cooling_run_time: 1s
    cool_deadband: 0.2°C
    cool_overrun:  0.2°C
    cool_action:
      - if:
          condition:
            - switch.is_on: ${node_name}_controller_mode
          then:
            - switch.turn_off: ${node_name}_mixing_valve_actuator_increase
            - switch.turn_on:  ${node_name}_mixing_valve_actuator_decrease
    # Increase mixing ratio
    min_heating_off_time: 1s
    min_heating_run_time: 1s
    heat_deadband: 0.2°C
    heat_overrun:  0.2°C
    heat_action:
      - if:
          condition:
            - switch.is_on: ${node_name}_controller_mode
          then:
            - switch.turn_off: ${node_name}_mixing_valve_actuator_decrease
            - switch.turn_on:  ${node_name}_mixing_valve_actuator_increase
    # Hold mixing ratio
    min_idle_time: 1s
    idle_action:
      - if:
          condition:
            - switch.is_on: ${node_name}_controller_mode
          then:
            - switch.turn_off: ${node_name}_mixing_valve_actuator_decrease
            - switch.turn_off: ${node_name}_mixing_valve_actuator_increase
    # Temperature presets and thermostat settings
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low:  21.4°C
        default_target_temperature_high: 21.0°C
      - name: Away
        default_target_temperature_low:  18.4°C
        default_target_temperature_high: 18.0°C
    visual:
      min_temperature: 15.0°C
      max_temperature: 35.0°C
      temperature_step: 0.1°C

# Mixing valve actuator operational indicators
binary_sensor:
  # Decrease indicator
  - platform: template
    name: $node_prefix minska
    id: ${node_name}_mixing_valve_status_decrease
    icon: mdi:minus-circle
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( id(${node_name}_mixing_valve_actuator_decrease).state )
          return true;
      } else {
        if ( id(mixing_valve_manual_decrease).state )
          return true;
      }
      return false;
  # Neutral indicator
  - platform: template
    name: $node_prefix neutral
    id: ${node_name}_mixing_valve_status_neutral
    icon: mdi:circle-outline
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( (id(${node_name}_mixing_valve_actuator_decrease).state == 0) && 
             (id(${node_name}_mixing_valve_actuator_increase).state == 0) )
          return true;
      } else {
        if ( (id(mixing_valve_manual_decrease).state == 0) &&
             (id(mixing_valve_manual_increase).state == 0) )
          return true;
      }
      return false;
  # Increase indicator
  - platform: template
    name: $node_prefix öka
    id: ${node_name}_mixing_valve_status_increase
    icon: mdi:plus-circle
    filters:
      - delayed_on_off: 400ms
    lambda: |-
      if ( id(${node_name}_controller_mode).state ) {
        if ( id(${node_name}_mixing_valve_actuator_increase).state )
          return true;
      } else {
        if ( id(mixing_valve_manual_increase).state )
          return true;
      }
      return false;

# Mixing valve actuator position counter
number:
  - platform: template
    name: $node_prefix läge
    id: ${node_name}_mixing_valve_position_counter
    icon: mdi:knob
    unit_of_measurement: ""
    initial_value: 0
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 240
    step: 1
    mode: slider
