#
# ESP32 SSR Mixing Valve Controller
#
# https://github.com/jnasholm/mvc-pwm/tree/main
#
# Main configuration
#
substitutions:
  node_name: gvs
  node_prefix: GVS

# Board configuration
esphome:
  project:
    name: "jnasholm.mvc-pwm"
    version: "0.3"
  name: $node_name
  friendly_name: $node_prefix
  comment: Mixing Valve Controller
  min_version: 2025.4.0

# Flash write interval
preferences:
  flash_write_interval: 20min

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_api_key

# Enable OTA
ota:
  - platform: esphome
    password: !secret ota_password

# Node switches
switch:
  - platform: restart
    name: Starta om nod
#  - platform: shutdown
#    name: Stäng av nod

# Node uptime
sensor:
  - platform: uptime
    name: Drifttid
    icon: mdi:timer-outline
    update_interval: 60s

# Include packages
packages:
  boardconfig: !include boardconfig.yaml
#  ethernet: !include ethernet.yaml
#  battery: !include battery.yaml
  time: !include time.yaml
  status: !include status.yaml
  controls: !include controls.yaml
#  homeassistant: !include sensors-homeassistant.yaml
  line_temp: !include sensors-line_temp.yaml
  outdoor_temp: !include sensors-outdoor_temp.yaml
  supply_line: !include control-supply_line.yaml
  mixing_valve: !include control-mixing_valve.yaml
