# Line temperature sensor configuration

# Input configuration line temperatures
one_wire:
  - platform: gpio
    pin: GPIO27
    #pin: GPIO25
    id: line_temperature_bus

# Floor heating distributor temperatures
sensor:
  # Supply line temperature
  - platform: dallas_temp
    name: $node_prefix tillopp
    id: ${node_name}_supply_line_temperature
    update_interval: 10s
    one_wire_id: line_temperature_bus
    address: 0xfb00000e17852028
    resolution: 12
    accuracy_decimals: 2
  # Return line temperature
  - platform: dallas_temp
    name: $node_prefix retur
    id: ${node_name}_return_line_temperature
    update_interval: 10s
    one_wire_id: line_temperature_bus
    address: 0xd000000e17e5ce28
    resolution: 12
    accuracy_decimals: 2
  # Mixing line temperature
  - platform: dallas_temp
    name: $node_prefix blandning
    id: ${node_name}_mixing_line_temperature
    update_interval: 10s
    one_wire_id: line_temperature_bus
    address: 0x3400000e6129a928
    resolution: 12
    accuracy_decimals: 2
  # Supply line temperature median
  - platform: template
    name: $node_prefix tillopp medel
    id: ${node_name}_supply_line_temperature_median
    icon: mdi:thermometer
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 10s
    lambda: return (id(${node_name}_supply_line_temperature).state);
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
      - heartbeat: 10s
  # Supply and return line temperature difference
  - platform: template
    name: $node_prefix värmebehov
    id: ${node_name}_line_temperature_difference
    icon: mdi:thermometer
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
      float sl_temp = id(${node_name}_supply_line_temperature).state;
      float rl_temp = id(${node_name}_return_line_temperature).state;
      return sl_temp - rl_temp;

## Heat source supply and return lines
#  - platform: dallas_temp
#    name: $node_prefix framledning
#    id: ${node_name}_supply_line_temperature
#    update_interval: 20s
#    one_wire_id: line_temperature_bus
#    address: 0x7400000CAE1E8328
#    resolution: 12
#  - platform: dallas_temp
#    name: $node_prefix returledning
#    id: ${node_name}_return_line_temperature
#    update_interval: 20s
#    one_wire_id: line_temperature_bus
#    address: 0x1200000CA4CD1728
#    resolution: 12
