# Outdoor temperature sensor configuration

# Input configuration outdoor temperatures
dallas:
  - pin: GPIO14
    update_interval: 10s

# Outdoor temperature
sensor:
  - platform: dallas
    name: $node_prefix utetemperatur
    id: outdoor_temperature
    address: 0x6C00000CA32B7B_S10
    resolution: 12

# Analog temperature sensor
# NTC Beta factor calculated according to the equation below
# https://www.ametherm.com/thermistor/ntc-thermistor-beta
  - platform: ntc
    name: $node_prefix utetemperatur analog
    sensor: outdoor_temperature_analog
    calibration:
      b_constant: 3919
      reference_temperature: 5°C
      reference_resistance: 5.66kOhm
# Calibration points for UVEAB EVR-U according to documentation
#    calibration:
#      - 43.03kOhm -> -30°C
#      - 31.09kOhm -> -25°C
#      - 22.76kOhm -> -20°C
#      - 16.86kOhm -> -15°C
#      - 12.63kOhm -> -10°C
#      - 9.57kOhm -> -5°C
#      - 7.32kOhm -> 0°C
#      - 5.66kOhm -> 5°C
#      - 4.41kOhm -> 10°C
#      - 3.47kOhm -> 15°C
#      - 2.75kOhm -> 20°C
#      - 2.20kOhm -> 25°C
  - platform: resistance
    name: $node_prefix utetemperatur analog sensor
    id: outdoor_temperature_analog
    sensor: outdoor_temperature_analog_sensor
    configuration: DOWNSTREAM
    resistor: 1.0kOhm
  - platform: adc
    id: outdoor_temperature_analog_sensor
    pin: GPIO34
    update_interval: never

# Analog temperature sensor power source
switch:
  - platform: gpio
    pin: GPIO13
    id: outdoor_analog_sensor_power

# Analog temperature sensor update interval
interval:
  - interval: 60s
    then:
      - switch.turn_on: outdoor_analog_sensor_power
      - component.update: outdoor_temperature_analog_sensor
      - switch.turn_off: outdoor_analog_sensor_power
