# Line temperature sensor configuration

# Input configuration line temperatures
dallas:
  - pin: GPIO27
    id: line_temperature_bus
    update_interval: 10s

# Floor heating distributor supply, return and mixing lines
sensor:
  # Supply line temperature
  - platform: dallas
    name: $node_prefix tillopp
    id: ${node_name}_supply_line_temperature
    dallas_id: line_temperature_bus
    address: 0x6C00000CA32B7B
    resolution: 12
  # Return line temperature
  - platform: dallas
    name: $node_prefix retur
    id: ${node_name}_return_line_temperature
    dallas_id: line_temperature_bus
    address: 0x6C00000CA32B6B
    resolution: 12
  # Mixing line temperature
  - platform: dallas
    name: $node_prefix blandning
    id: ${node_name}_mixing_line_temperature
    dallas_id: line_temperature_bus
    address: 0x6C00000CA32B5B
    resolution: 12
