# Outdoor temperature sensor configuration

# Digital outdoor temperature sensor bus configuration
#one_wire:
#  - platform: gpio
#    id: outdoor_temperature_bus
#    pin: $digital_temp_pin

# Broadcast providers
substitutions:
  temperature_provider_node_name: et

# Packet transport configuration
udp:

# Broadcast provider configuration
packet_transport:
  - platform: udp
    id: transport_input
    providers:
      - name: $temperature_provider_node_name
        encryption: !secret broadcast_key

# Sensor configurations
sensor:
  # Active outdoor temperature sensor (automatic fail-over with backup value)
  - platform: template
    name: Utetemperatur
    id: outdoor_temperature
    icon: mdi:thermometer
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 20s
    lambda: |-
      if ( id(${node_name}_connection_status).state ) {
        if ( !isnan(id(outdoor_temperature_remote).state) )
          return id(outdoor_temperature_remote).state;
        if ( !isnan(id(outdoor_temperature_broadcast).state) )
          return id(outdoor_temperature_broadcast).state;
      }
      if ( !isnan(id(outdoor_temperature_analog).state) )
        return id(outdoor_temperature_analog).state;
      //if ( !isnan(id(outdoor_temperature_digital).state) )
      //  return id(outdoor_temperature_digital).state;
      return 8.0;

  # Remote outdoor temperature sensor (Home Assistant)
  - platform: homeassistant
    id: outdoor_temperature_remote
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    entity_id: sensor.utetemperatur
    filters:
      - heartbeat: 20s

  # Remote outdoor temperature sensor (Broadcast)
  - platform: packet_transport
    id: outdoor_temperature_broadcast
    transport_id: transport_input
    provider: $temperature_provider_node_name
    remote_id: outdoor_temperature
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2

#  # Digital outdoor temperature sensor (DS18B20)
#  - platform: dallas_temp
#    name: Utetemperatur digital
#    id: outdoor_temperature_digital
#    accuracy_decimals: 2
#    update_interval: 20s
#    one_wire_id: outdoor_temperature_bus
#    address: 0x2c0000081d200d28
#    resolution: 12

  # Analog outdoor temperature sensor (NTC)
  # NTC Beta factor calculated according to the equation below
  # https://www.ametherm.com/thermistor/ntc-thermistor-beta
  - platform: ntc
    name: Utetemperatur analog
    id: outdoor_temperature_analog
    accuracy_decimals: 2
    sensor: outdoor_temperature_analog_sensor
    # NTC Beta factor calibration
#    calibration:
#      b_constant: 3919
#      reference_temperature: 5°C
#      reference_resistance: 5.66kOhm
    # NTC calibration points for UVEAB EVR-U according to documentation.
    calibration:
    # - 43.03kOhm -> -30°C
    # - 31.09kOhm -> -25°C
    # - 22.76kOhm -> -20°C
    # - 16.86kOhm -> -15°C
      - 12.63kOhm -> -10°C
    # - 9.57kOhm -> -5°C
    # - 7.32kOhm -> 0°C
      - 5.66kOhm -> 5°C
    # - 4.41kOhm -> 10°C
    # - 3.47kOhm -> 15°C
      - 2.75kOhm -> 20°C
    # - 2.20kOhm -> 25°C
    filters:
      - sliding_window_moving_average:
          window_size: 9
          send_every: 1
          send_first_at: 1
#      - offset: -0.4
  # Resistance calculation
  - platform: resistance
    name: Utetemperatur analog sensor
    id: outdoor_temperature_analog_sensor
    icon: mdi:omega
    sensor: outdoor_temperature_analog_measure
    configuration: DOWNSTREAM
    resistor: 10kOhm
  # Voltage measurement (range 0.15-2.45V)
  - platform: adc
    id: outdoor_temperature_analog_measure
    pin: $analog_temp_pin
    update_interval: never
    attenuation: 12db
    filters:
      - exponential_moving_average:
          alpha: 0.06
          send_every: 3
          send_first_at: 1

# Analog temperature sensor power source configuration
switch:
  - platform: gpio
    pin: $analog_power_pin
    id: outdoor_analog_sensor_power

# Analog temperature sensor update interval
interval:
  - interval: 20s
    then:
      - switch.turn_on: outdoor_analog_sensor_power
      - delay: 1s
      - component.update: outdoor_temperature_analog_measure
      - delay: 1s
      - switch.turn_off: outdoor_analog_sensor_power
