# WiFi configuration
wifi:
  networks:
  - id: wifi_net_1
    ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
    priority: 4
  - id: wifi_net_2
    ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
    priority: 0
  min_auth_mode: WPA2
  reboot_timeout: 0s
  ap:
    ssid: $node_name network
    password: !secret fallback_password

# Captive portal
captive_portal:

# WiFi information sensors
sensor:
  - platform: wifi_signal
    name: Signalstyrka
    icon: mdi:signal-cellular-3
    update_interval: 60s
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
      icon: mdi:ip-network-outline
    mac_address:
      name: MAC
      icon: mdi:network-outline
    ssid:
      name: Nätverk
      icon: mdi:wifi

# Web server settings
web_server:
  port: 80
  ota: false
